### ISSUE TITLE
提供 JSON 格式

### ISSUE THREAD

**Issue by ghost** [lyc8503/sing-box-rules#6]
JSON 格式并非用于加载，其设计初衷仅为便于阅读。参见 https://github.com/SagerNet/sing-box/issues/1189#issuecomment-1857893599

生成 JSON 格式的具体方法，详见 https://github.com/xmdhs/sing-geosite

上游代码已更新。查看 https://github.com/SagerNet/sing-geoip 以及 https://github.com/SagerNet/sing-geosite

**Comment by lyc8503** [comment]
我看上游这边也没在 Release 中提供 JSON 文件，我最近也没有很多时间研究这个，抱歉。

如果有 PR 的话我可以合并一下。

**Comment by lyc8503** [comment]
Fixed in #8
