### ISSUE TITLE
请问这些文件的remote download url是什么？

### ISSUE THREAD

**Issue by itispip** [lyc8503/sing-box-rules#7]
例如在官网的示例,是有remote下载地址

    "rule_set": [
      {
        "tag": "geosite-cn",
        "type": "remote",
        "format": "binary",
        **"url": "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs",**
        "download_detour": "proxy"
      }

**Comment by lyc8503** [comment]
如果你需要的是 srs 文件，下载地址如下：

https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-cn.srs
